theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true
